name: Tmate Debug

on:
  workflow_dispatch:

jobs:
  debug:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - name: Start tmate session
        uses: mxschmitt/action-tmate@v3
        with:
          detached: false
          limit-access-to-actor: false
